name: Daily Zepp Steps

on:
  schedule:
    # 对应北京时间：早上 05:00 (UTC 21:00)
    - cron: '0 21 * * *'
    # 对应北京时间：上午 10:00 (UTC 02:00)
    - cron: '0 2 * * *'

  workflow_dispatch:

jobs:
  run-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pytz

      - name: Run the script
        env:
          ZEPP_USER: ${{ secrets.ZEPP_USER }}
          ZEPP_PASS: ${{ secrets.ZEPP_PASS }}
        run: |
          python main.py
